name: Deploy to GCP

on:
  push:
    branches: [ master ]

env:
  RUN_REGION: europe-west1
  SERVICE_NAME: chatgpt-telegram-bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE_NAME" \
          --region "$RUN_REGION" \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}