name: Deploy to GCP

on:
  push:
    branches: [ master ]

env:
  SERVICE_NAME: chatgpt-telegram-bot
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Push
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy
        run: |
          gcloud container clusters get-credentials cluster-1 \
            --location us-central1-c
          helm upgrade $SERVICE_NAME ./helm-chart \
            --wait
          kubectl rollout status deployment/$SERVICE_NAME
          kubectl get services -o wide
