name: Deploy to GCP

on:
  push:
    branches: [ master ]

env:
  SERVICE_NAME: chatgpt-telegram-bot
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.GITHUB_SHA }} .

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.GITHUB_SHA }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Authenticate to GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: cluster-1
          location: us-central1-c

      - name: Deploy Application
        run: |
          helm upgrade --install ${{ env.SERVICE_NAME }} ./helm-chart \
            --set 'SERVICE_NAME=${{ env.SERVICE_NAME }}' \
            --set 'IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.GITHUB_SHA }}' \
            --set 'TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}' \
            --set 'GPT_TOKEN=${{ secrets.GPT_TOKEN }}' \
            --set 'TELEGRAM_AUTHORIZED_USER_IDS=${{ secrets.TELEGRAM_AUTHORIZED_USER_IDS }}' \
            --wait